steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - build

  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - push

  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployments/nemov-nestjs
      - mybackend10-nestjs-sha256-1=asia.gcr.io/nemo-v-backend/mybackend10-nestjs:0.9.2
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1
